---
# tasks file for puppet
- name: Instala o PuppetServer
  package:
    name: puppetserver
    update_cache: yes
  when: ansible_hostname == "devops"

- name: Instala o PuppetAgent
  package:
    name: puppet-agent
    update_cache: yes
