---
# tasks file for puppet
- name: Instala repositorio puppet CentOS7
  yum:
    name: https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm
  when: 
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"

- name: Instala repositorio puppet Ubuntu16
  apt:
    deb: https://apt.puppetlabs.com/puppet5-release-xenial.deb
  when: 
    - ansible_os_family == "Debian"
    - ansible_distribution_major_version == "16"
